PrimerParcialSanMartin/Controllers/CursosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PrimerParcialSanMartin.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace PrimerParcialSanMartin.Controllers
{
    public class CursosController : Controller
    {
        private readonly IWebHostEnvironment Hosting;
        private readonly AcademiaDbContext db;
        public CursosController(IWebHostEnvironment hosting, AcademiaDbContext ctx)
        {
            db=ctx;
            Hosting = hosting;
        }
        
        public IActionResult Index(string CampoOrden, string busquedaNombre)
        {

            var listadoOrdenado = db.Cursos.Include(x => x.TipoCursada).ToList();
            if (!(String.IsNullOrEmpty(busquedaNombre)))
            {
                listadoOrdenado = listadoOrdenado.Where(x => x.Nombre.ToUpper().Contains(busquedaNombre.ToUpper()) || x.ProfesorACargo.ToUpper().Contains(busquedaNombre.ToUpper())).ToList();
            }
            

            switch (CampoOrden)
            {
                case "curso":
                    listadoOrdenado = listadoOrdenado.OrderBy(x => x.CodigoCurso).ToList();
                    break;
                case "nombre_curso":
                    listadoOrdenado = listadoOrdenado.OrderBy(x => x.Nombre).ToList();
                    break;
                case "duracion":
                    listadoOrdenado = listadoOrdenado.OrderBy(x => x.Duracion).ToList();
                    break;
                case "profesor":
                    listadoOrdenado = listadoOrdenado.OrderBy(x => x.ProfesorACargo).ToList();
                    break;
                default:
                    listadoOrdenado = listadoOrdenado.OrderBy(x => x.CodigoCurso).ToList();
                    break;
            }
            return View(listadoOrdenado);
        }
        public IActionResult Editar(int codigo)
        {
            var cursoBuscado = db.Cursos.Include(x => x.TipoCursada).ToList().Where(c => c.CodigoCurso == codigo).FirstOrDefault();
            
            ViewBag.Titulo = "Estamos editando a: " + cursoBuscado.Nombre;
            var cursadasDB = db.TipoCursadas.ToList();
            ViewBag.TipoCursada = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(cursadasDB, "Codigo", "Nombre");

            if (!String.IsNullOrEmpty(cursoBuscado.FotoRuta))
            {
                string Carpeta = Path.Combine(Hosting.WebRootPath, "imagenes");
                string rutadestino = Path.Combine(Carpeta, cursoBuscado.FotoRuta);
                var streamArchivo = System.IO.File.OpenRead(rutadestino);
                cursoBuscado.Foto = new FormFile(streamArchivo, 0, streamArchivo.Length, null, Path.GetFileName(streamArchivo.Name));
            }
            return View(cursoBuscado);
        }

        [HttpPost]
        public IActionResult Editar(Curso curform)
        {
            if (ModelState.IsValid)
            {
                Curso cursoAnterior = db.Cursos.Include(x => x.TipoCursada).ToList().Where(c => c.CodigoCurso == curform.CodigoCurso).FirstOrDefault();
                {
                    //si la foto es null no guardar nada sino si
                    if (curform.Foto != null)
                    {
                        curform.FotoRuta = GuardarImagen(curform.Foto).Result;
                        
                    }
                    db.Cursos.Remove(cursoAnterior);
                    db.Cursos.Add(curform);
                    db.SaveChanges();
                    
                }
                
                return RedirectToAction("Index");
            }
            return View(curform);
        }

        public IActionResult Crear()
        {
            ViewBag.TipoCursada = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(db.TipoCursadas, "Codigo", "Nombre");
            return View();
        }

        [HttpPost]
        public IActionResult Crear(Curso curform)
        {
            ViewBag.TipoCursada = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(db.TipoCursadas, "Codigo", "Nombre");

            if (ModelState.IsValid)
            {
                if (ValidarExisteCodigo(curform.CodigoCurso))
                {
                    ModelState.AddModelError("CodigoCurso", "El codigo ya existe");
                }
                else
                {

                    curform.FotoRuta = GuardarImagen(curform.Foto).Result;
                    db.Cursos.Add(curform);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                
            }
            return View(curform);
            
        }

        public IActionResult Ver(int codigo)
        {
            var cursoBuscado = db.Cursos.ToList().Where(c => c.CodigoCurso == codigo).FirstOrDefault();
            ViewBag.Titulo = "Estamos viendo al curso: " + cursoBuscado.Nombre;
            ViewBag.TipoCursada = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(db.TipoCursadas.ToList(), "Nombre", "Nombre");
            return View(cursoBuscado);
        }
        
        public IActionResult Eliminar(int codigo)
        {
            var productoOriginal = db.Cursos.ToList().Where(x => x.CodigoCurso == codigo).FirstOrDefault();
            db.Cursos.Remove(productoOriginal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public bool ValidarExisteCodigo(int? codigo)
        {
            return db.Cursos.ToList().Exists(x => x.CodigoCurso == codigo);
        }
        private async Task<string> GuardarImagen(IFormFile Foto)
        {
            if (Foto != null)
            {
                string NombreArchivo = Foto.FileName;
                string Carpeta = Path.Combine(Hosting.WebRootPath, "imagenes");
                string rutadestino = Path.Combine(Carpeta, NombreArchivo);
                using(Stream fileStream = new FileStream(rutadestino, FileMode.Create))
                {
                    await Foto.CopyToAsync(fileStream);
                }
                return NombreArchivo;
            }
            return "";
        }
    }

}

PrimerParcialSanMartin/Views/Shared/_CalculoPagoSemanal.cshtml
@model Curso

@functions{
        string CalcularPagoXSemana(TipoCursada tipo, int? duracion, string profesor){
        
        int valorXHora = 0;
        switch(tipo.Nombre) {
            case "Presencial": 
                    valorXHora = 150;
                break;
            case "Virtual": 
                    valorXHora = 80;
                break;    
            case "Bimodal":
                    valorXHora = 100;
                break;            
        }
        
        double pagoSemanal = duracion.GetValueOrDefault() * valorXHora;

        <div class="alert alert-primary" role="alert">
                <h4 class="alert-heading">Sueldo por clase y tipo de cursada</h4>
                <p>El sueldo semanal de @profesor es $@pagoSemanal. </p>
        </div>
        return string.Empty;
    }
}
<div class="form-row">
    <div class="col-6">
        @CalcularPagoXSemana(Model.TipoCursada, Model.Duracion, Model.ProfesorACargo)
    </div>    
</div>

PrimerParcialSanMartin/Views/Shared/_CantCursos.cshtml
@model List<Curso>

<p>Hay @Model.Count() cursos cargados.</p>

PrimerParcialSanMartin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimerParcialSanMartin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Academia de Musica San Martin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cursos" asp-action="Index">Cursos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PrimerParcialSanMartin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>